### ISSUE TITLE
Ukol01-Baliky / Dominika Langova

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#1]
https://github.com/lang-do/python-ukoly/blob/main/ukol-1.py
Ahoj,
posílám odkaz na můj úkol.
Předem děkuji za opravu,
Hezký večer,
Dominika

**Comment by AnetaPopelova** [comment]
Ahoj, diky za odevzdani ukolu!

Tvuj kod ted spravne kontroluje, jestli je kod baliku jako klic ve slovniku 👍 
Je treba jeste doplnit podminku, ktera zkontroluje, jestli byl predan dopravci. 

_Zadani: Pokud byl předán, má hodnotu True, v opačném případě má hodnotu False._

Zkus to tam pridat a napis mi tu kratkou zpravu, at vim, ze se na to muzu znovu kouknout.

**Comment by lang-do** [comment]
Ahoj,
děkuju za opravu, už jsem to opravila (zdálo se mi to podezřele jednoduché :D ale aspoň si procvičím to nahrávání úkolů :D).

Mockrát děkuju za kontrolu.

**Comment by AnetaPopelova** [comment]
💯 Super!
