### ISSUE TITLE
ukol11 - regex PSC / Dominika Langova

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#10]
https://github.com/lang-do/python-ukoly/blob/main/jupyter-notebook/ukol-11.ipynb

Ahoj Anet,
posílám vypracovaný úkol č. 11.
Děkuji mockrát za opravu a přeji krásný večer,
Dominika

**Comment by AnetaPopelova** [comment]
Fajn, ale pozor na `\s` -  to jsou vsechny _„bílé” znaky (mezera, tabulátor, znaky pro zalomení řádků)_. Ne pouze mezery. 

A tohle by pripadne taky udelalo dobrou sluzbu `r"\d{3} \d{2}[a-Ž ]+ \d+"` ;-)
