### ISSUE TITLE
ukol12 - histogram / Dominika Langova

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#12]
https://github.com/lang-do/python-ukoly/blob/main/jupyter-notebook/ukol-12.ipynb

Ahoj Anet,
posílám odkaz na vypracovaný úkol č. 12.
Děkuji za opravu a přeji krásný večer,
Dominika

**Comment by AnetaPopelova** [comment]
Teda, to je rychlost 💯 

Gratuluji, jako prvni z celeho kurzu mas 12/12 🥇 
![Screenshot 2022-12-06 at 22 13 36](https://user-images.githubusercontent.com/47115025/206024479-c785d69f-88a2-45dc-8b59-edbbc540644b.png)

**Comment by lang-do** [comment]
Jupíí :)) Anet mockrát děkuju za laskavost u opravy úkolů a všechny rady! Kurz byl vážně super a je krásný s jakou lehkostí se s Czechitas člověk může ponořit do náročnejch věcí :)
