### ISSUE TITLE
ukol02-slovniky

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#2]
https://github.com/lang-do/python-ukoly/blob/main/ukol-2.py

Pěkný večer,

posílám odkaz na vypracovaný úkol, nad bonusem se bohužel neúspěšně trpím. Zvládla jsem vypsat součty populací všech subregionů, zvládla jsem si udělat slovník s konkrétními subregiony pro region dle inputu, ale nedokážu to spoji, ,abych si program nerozbila. Mohla bych poprosit o radu?

Mockrát děkuji za opravu a přeji krásný večer.
Dominika

**Comment by AnetaPopelova** [comment]
Ahoj, prochazim to a napada me:

Prevadet dictionary na seznam je ehm.. neoptimalni. Ztratis tim vsechny vyhody slovniku. Asi chapu, ze jsi tim chtela vyresit problem s vracenim "neznamy region"... ale cele `if value in list:` je zbytecne... Davam ti ale bod za kreativitu!

Zkusila bych vytvorit si seznam unikatnich regionu ze slovniku a ten pak kontrolovat. [Tady](https://python1podzim2022.slack.com/archives/C0441KMGFFF/p1664869998035909?thread_ts=1664831423.268239&cid=C0441KMGFFF) Andy popisuje zajimavy pristup.

Bonus:
Zacatek je stejny jako prve:

- projdes vsechny staty ve slovniku `for stat in staty:`
- vyfiltrujes si spravny region ` if stat['region'] == value:`
- a pak si muzes pouzit tohle, to mas moc hezky!
```
 subregion = stat['subregion']
    population = stat['population']
    if subregion in sum_pop_reg:
        sum_pop_reg[subregion] += population
    else:
        sum_pop_reg[subregion] = population
```
A voila, v promenne `sum_pop_reg` mas vysledek!
Vsechno to tam mas, je to trochu preskladat.

Vytvaret `subregionList` a ta posledni iterace `for subregion, population in sum_pop_reg.items():` je zbytecne, ale libi semi, jak uvazujes :-)

P.S.: na prvnim radku ti zbyl zbytecny import?

**Comment by lang-do** [comment]
Ahoj Anet,

mockrát děkuji za opravu! Přišlo mi, že na to jdu oklikou, ale když už to fungovalo, tak mi bylo líto to mazat, ale chtělo to jít od začátku :D
už mi funguje i bonus jupí https://github.com/lang-do/python-ukoly/blob/main/ukol-2.py

Mockrát děkuju za opravu,
Krásný večer,
Dominika

**Comment by AnetaPopelova** [comment]
Jako... takhle jsem to uplne nemyslela, ale funguje to :-D 

Za me ok👍
