### ISSUE TITLE
ukol03 - sms / Dominika Langova

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#3]
https://github.com/lang-do/python-ukoly/blob/main/ukol-3.py

Ahoj Anet,

zasílám odkaz na vypracovaný úkol:)

Děkuju za opravu a přeji krásný večer,
Dominika

**Comment by AnetaPopelova** [comment]
Ahoj :-)

Hm. Funguje to "spravne", ale mam par poznamek:

Dle zadani maji existovat **dve** samostatne funkce (pro kontrolu cisla a pro vypocet ceny). 

Argumentem funkce by melo byt telefonni cislo resp. text zpravy. 

Zaroven ty funkce typicky vraceji (return) nejakou hodnotu, kterou pak muzes pouzit dal (informaci o spravnosti resp. o cene).

Predstav si, ze tech cisel jsou tisice a ty chces overit kazde. 

Zkus se na to prosim jeste podivat.

**Comment by lang-do** [comment]
Ahoj,

děkuji za opravu, tady jsem vytvořila funkci i pro výpočet ceny zprávy
https://github.com/lang-do/python-ukoly/blob/main/ukol-3.py
snad to je už správně :)

Děkuji za opravu a komentáře.
Hezký den,
Dominika

**Comment by AnetaPopelova** [comment]
Posilam jednu z variant reseni. Jen na ni prosim koukni, pro predstavu - zvlast na to, co je vstupem do funkci a jak se volaji.

```
import math

def validate_number(phone_number):
	phone_number = phone_number.replace(' ', '')
	if len(phone_number) == 9:
		return True
	elif len(phone_number) == 13 and phone_number[0:4] == '+420':
		return True
	else:
		return False
		
def get_price(message):
	num_char = len(message)
	num_messages = math.ceil(num_char / 180)
	return num_messages * 3

phone_number_input = input('Zadejte telefonni cislo adresata: ')
if validate_number(phone_number_input):
  message_input = input('Zadejte text zpravy: ')
  messege_price = get_price(message_input)
  print(f'Cena zpravy je {messege_price} Kč.')
else:
	print('Chybny format telefonniho cisla.')
```
