### ISSUE TITLE
 ukol05 - covid / Dominika Langova

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#5]
https://github.com/lang-do/python-ukoly/blob/main/ukol-5_1.py

Ahoj Anet,

posílám odkaz na vypracovaný úkol z lekce 5 (dědičnost).

Děkuju za opravu a doufám, že už Ti je líp :)
Dominika

**Comment by AnetaPopelova** [comment]
To je radost cist 👍
