### ISSUE TITLE
ukol07 - vstupenky / Dominika Langova

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#6]
https://github.com/lang-do/python-ukoly/blob/main/jupyter-notebook/ukol-7.ipynb

Ahoj Anet,
zasílám úkol č. 7 a musim říct, že jsem z jupyteru nadšená :)

Děkuju za opravu,
Hezký večer,
Dominika

**Comment by AnetaPopelova** [comment]
Fajn 👍 

Pozor na ty importy:

```
import datetime as dt
from datetime import datetime, timedelta, date, timezone
```

- nejdriv importujes cely modul a das mu alias dt
- pak to prepises importem trid v nem obsazenych, z nichz vetsinu importujes zbytecne (to se snazime nedelat, aby byl vysledny kod cistejsi a prehlednejsi)

Pro tvuj kod by stacilo:
```
from datetime import datetime
```
