### ISSUE TITLE
ukol06 - změna dat v souboru / Dominika Langova

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#7]
https://github.com/lang-do/python-ukoly/blob/main/ukol-6.py

Ahoj Anet,

posílám odkaz na vypracovaný úkol č. 6.

Děkuji za opravu a přeju krásný zbytek večera,
Dominika

**Comment by AnetaPopelova** [comment]
Super reseni s tim slovnikem 🥇 👍 

Jen bych zvazila rozlozeni nacteni souboru a provadeni zmen do dvou kroku - kvuli citelnosti a variabilite.
