### ISSUE TITLE
ukol08 - pandas adopce zvirat / Dominika Langova

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#8]
https://github.com/lang-do/python-ukoly/blob/main/jupyter-notebook/ukol-8.ipynb

Ahoj Anet,

posílám odaz na vypracovaný úkol.

Předem děkuji za opravu a přeji krásný večer,
Dominika

**Comment by AnetaPopelova** [comment]
Super! 👍 

Jedine, co k tomu muzu podotknout je, ze dataframe s serazenym indexem mel prepsat puvodni tabulku, ty jsi vytvorila dalsi (ac chapu proc).
