### ISSUE TITLE
ukol09 - teplota / Dominika Langova

### ISSUE THREAD

**Issue by lang-do** [lang-do/python-ukoly#9]
https://github.com/lang-do/python-ukoly/blob/main/jupyter-notebook/ukol-9.ipynb

Ahoj Anet,
posílám odkaz na zpracovaný úkol č. 9.
Děkuji za opravu a přeji krásný večer,
Dominika

**Comment by AnetaPopelova** [comment]
Ahoj, je to fajn - ale pozor: `index` by měl být jedinečným identifikátorem konkrétního řádku. A protože pro každé město máme více záznamů, nehodí se město jako index. Číselný index je v tomhle případě naprosto ok. 

A prosím, zvaž pojmenovávání proměnných.

- měl by to být `snake_case`
- mělo by to být popisné (aby to každý pochopil na první pohled) - místo `notColdEuC` třeba `europe_cities_not_cold`
